#pragma once

#include <memory>
#include <vector>
#include <libassert/assert.hpp>

#include "asset_id.hpp"


namespace siren {

// todo: i think we need to use mutex on ref counts here since handle be dropping these from any threads

template <IsAsset A>
class AssetPool;

/** @brief Base AssetPool class used for polymorphism. */
class AssetPoolBase {
public:
    virtual ~AssetPoolBase() = default;

    /** @brief Returns the TypeID of the asset type this loader manages. */
    [[nodiscard]] virtual auto type_id() const noexcept -> AssetId::TypeID = 0;
};

/**
 * @brief The means of asset storage in siren. Manages
 * asset lifetime as well as providing AssetID's and AssetHandle's.
 * @tparam A The asset type this pool stores.
 */
template <IsAsset A>
class AssetPool final : public AssetPoolBase {
public:
    using GenerationType = AssetId::GenerationType;
    using IndexType      = AssetId::IndexType;
    using TypeID         = AssetId::TypeID;
    using RefCount       = u32;

    ~AssetPool() override = default;

private:
    friend class AssetServer;
    friend class LoadContext;

    /** @brief A storage element in the AssetPool. */
    struct PoolEntry {
        /** @brief The stored asset. */
        std::unique_ptr<A> asset  = nullptr;
        /** @brief The generation of this storage slot. Useful for reusing slots. */
        GenerationType generation = 0;
        /** @brief The number of handles referencing this asset. */
        RefCount ref_count        = 0;

        // @formatter:off
        void kill() { asset.reset(nullptr); generation++; ref_count = 0; }
        // @formatter:on
    };

    /** @brief The AssetPool's data. */
    struct AssetPoolData {
        /** @brief Dense asset storage. */
        std::vector<PoolEntry> storage;
        /** @brief Indices that have been freed and should be used. */
        std::vector<IndexType> free_list;
    };

public:
    [[nodiscard]] auto type_id() const noexcept -> AssetId::TypeID  override { return AssetId::type_id<A>(); }

    /** @brief Creates a new AssetID for this pool, as well as allocates it a storage slot. */
    [[nodiscard]] auto reserve() -> AssetId {
        IndexType idx;

        if (!m_data.free_list.empty()) {
            idx = m_data.free_list.back();
            m_data.free_list.pop_back();
        } else {
            idx = static_cast<IndexType>(m_data.storage.size());
            m_data.storage.emplace_back(); // grow storage so we don't mess array indexing up
        }

        auto& pool_entry     = m_data.storage[idx];
        pool_entry.asset     = nullptr;
        pool_entry.ref_count = 0;

        return AssetId{ idx, pool_entry.generation, AssetId::type_id<A>() };
    }

    /** @brief Adds an asset and takes ownership. */
    [[nodiscard]]
    auto add(std::unique_ptr<A>&& asset) -> AssetId {
        const AssetId id = reserve();
        PoolEntry& entry = m_data.storage[id.index()];
        entry.asset      = std::move(asset);
        return id;
    }

    /**
     * @brief Stores an asset into this pool and associates it with the given AssetID.
     * The ID should be generated by this pool.
     */
    auto link(const AssetId id, std::unique_ptr<A>&& asset) -> void {
        ASSERT(is_valid_id(id), "Invalid AssetID passed: {}", id);
        PoolEntry& entry = m_data.storage[id.index()];
        entry.asset      = std::move(asset);
    }

    /** @brief Returns the asset associated with the given ID, or nullptr. */
    [[nodiscard]]
    auto fetch(const AssetId id) const -> A* {
        if (!is_valid_id(id)) { return nullptr; }
        const PoolEntry& entry = m_data.storage[id.index()];
        return entry.asset.get();
    }

private:
    template <typename>
    friend class StrongHandle;

    auto is_valid_id(const AssetId id) const -> bool {
        if (id.index() >= m_data.storage.size() || !id.is_valid()) { return false; }
        const auto& entry = m_data.storage[id.index()];
        return entry.generation == id.generation();
    }

    auto inc_ref(const AssetId id) -> void {
        if (!is_valid_id(id)) { return; }
        PoolEntry& entry = m_data.storage[id.index()];
        entry.ref_count += 1;
    }

    auto dec_ref(const AssetId id) -> void {
        if (!is_valid_id(id)) { return; }

        PoolEntry& entry = m_data.storage[id.index()];

        // todo: we should maybe emit an AssetCleanupEvent? need to handle destruction here an in asset server eventually
        entry.ref_count -= 1;
        if (entry.ref_count == 0) {
            m_data.free_list.emplace_back(id.index());
            entry.kill();
        }
    }

    AssetPoolData m_data;
};
} // namespace siren
